@extends('layouts.pj')
@section('title', 'Laporan Galeri')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-4">
    <div><h4 class="fw-bold text-dark mb-1">🖼️ Laporan Album Dokumentasi</h4><p class="text-muted small mb-0">Review album visual kegiatan kebun raya.</p></div>
    <button type="button" class="btn text-white px-4 fw-bold shadow-sm" style="background-color: #1a5c2a; border-radius: 10px;" data-bs-toggle="modal" data-bs-target="#modalCetak">📂 Cetak Laporan</button>
</div>

{{-- Saringan Filter --}}
<div class="card border-0 shadow-sm mb-4" style="border-radius: 12px;"><div class="card-body p-3"><form action="{{ route('pj.laporan.galeri') }}" method="GET" class="row g-3 align-items-end"><div class="col-md-3"><label class="form-label small fw-bold text-muted mb-1">Paket Waktu:</label><select name="rentang_waktu" class="form-select form-select-sm" style="border-radius: 8px;"><option value="semua">✨ Semua Data</option><option value="tiga_bulan">📅 3 Bulan Terakhir</option><option value="enam_bulan">🗓️ 6 Bulan Terakhir</option></select></div><div class="col-md-3"><label class="form-label small fw-bold text-muted mb-1">Dari:</label><input type="date" name="tanggal_mulai" class="form-control form-control-sm" style="border-radius: 8px;"></div><div class="col-md-3"><label class="form-label small fw-bold text-muted mb-1">Sampai:</label><input type="date" name="tanggal_selesai" class="form-control form-control-sm" style="border-radius: 8px;"></div><div class="col-md-3"><button type="submit" class="btn btn-sm text-white w-100 fw-bold" style="background-color: #11411c; border-radius: 8px; height: 31px;">🔍 Terapkan</button></div></form></div></div>

<div class="row g-3">
    @forelse($albums as $album)
    <div class="col-md-4"><div class="card border-0 shadow-sm h-100" style="border-radius: 12px; overflow: hidden;"><div class="card-body p-3"><h6 class="fw-bold text-dark mb-1 text-truncate">📁 {{ $album->nama_album }}</h6><p class="text-muted small mb-2 text-truncate">{{ $album->deskripsi ?? 'Tidak ada deskripsi.' }}</p><span class="badge bg-success bg-opacity-10 text-success fw-bold"><i class="bi bi-image me-1"></i> {{ $album->galeris_count }} Berkas Foto</span></div></div></div>
    @empty<div class="col-12 text-center text-muted py-4">Belum ada album visual terdokumentasi.</div>@endforelse
</div>

{{-- MODAL PARAMETER POPUP CETAK --}}
<div class="modal fade" id="modalCetak" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content" style="border-radius: 15px;"><div class="modal-header text-white" style="background-color: #11411c; border-top-left-radius: 14px; border-top-right-radius: 14px;"><h5 class="modal-title fw-bold">🖨️ Cetak Laporan Galeri</h5><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><form action="{{ route('pj.laporan.export') }}" method="GET" target="_blank"><input type="hidden" name="jenis_laporan" value="galeri"><div class="modal-body p-4"><div class="mb-3"><label class="form-label fw-bold text-dark small">Pilihan Paket Cetak:</label><select name="rentang_cetak" class="form-select" style="border-radius: 8px;"><option value="semua">✨ Semua Album</option><option value="tiga_bulan">📅 3 Bulan Terakhir</option><option value="enam_bulan">🗓️ 6 Bulan Terakhir</option></select></div><div class="text-center my-3 position-relative"><hr><span class="position-absolute top-50 start-50 translate-middle bg-white px-2 text-muted small fw-bold">ATAU ATUR TANGGAL</span></div><div class="row g-2"><div class="col-6"><label class="form-label fw-bold text-dark small">Dari:</label><input type="date" name="cetak_tanggal_mulai" class="form-control" style="border-radius: 8px;"></div><div class="col-6"><label class="form-label fw-bold text-dark small">Sampai:</label><input type="date" name="cetak_tanggal_selesai" class="form-control" style="border-radius: 8px;"></div></div></div><div class="modal-footer bg-light" style="border-bottom-left-radius: 15px; border-bottom-right-radius: 15px;"><button type="button" class="btn btn-secondary fw-bold px-3" style="border-radius: 8px;" data-bs-dismiss="modal">Batal</button><button type="submit" class="btn text-white fw-bold px-4" style="background-color: #1a5c2a; border-radius: 8px;">Proses Cetak</button></div></form></div></div></div>
@endsection